{{- if .Values.moviezzz.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "apigw-demo.fullname" . }}-moviezzz
  labels:
    {{- include "apigw-demo.moviezzz.labels" . | nindent 4 }}
spec:
  type: {{ .Values.moviezzz.service.type }}
  ports:
    - port: {{ .Values.moviezzz.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "apigw-demo.moviezzz.selectorLabels" . | nindent 4 }}
{{- end }}
