{{- if .Values.parkruns.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "apigw-demo.fullname" . }}-parkruns
  labels:
    {{- include "apigw-demo.parkruns.labels" . | nindent 4 }}
spec:
  type: {{ .Values.parkruns.service.type }}
  ports:
    - port: {{ .Values.parkruns.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "apigw-demo.parkruns.selectorLabels" . | nindent 4 }}
{{- end }}
