{{- if eq (include "apigw-poc.kong.keycloak.enabledReady" .) "true" }}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: kong-manager-auth
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "apigw-poc.kong.labels" . | nindent 4 }}
spec:
  forwardAuth:
    address: http://kong-oauth2-proxy:4180/oauth2/auth
    trustForwardHeader: true
    authResponseHeaders:
      - X-Auth-Request-User
      - X-Auth-Request-Email
      - Authorization
{{- end }}

