{{- if .Values.producer.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: producer-service
  namespace: {{ .Values.producer.namespace }}
  labels:
    {{- include "apigw-poc.producer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.producer.service.type }}
  ports:
  - port: {{ .Values.producer.service.port }}
    targetPort: {{ .Values.producer.service.targetPort }}
    protocol: TCP
    name: http
  selector:
    app: {{ .Values.producer.name }}
{{- end }}
