# Generated by Django 4.2.16 on 2026-01-30 23:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('breed', models.CharField(max_length=100)),
                ('photo_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('caught_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'dogs',
                'ordering': ['-caught_date'],
            },
        ),
    ]
