replicaCount: 1

image:
  repository: docker.io/jimleitch/good-behaviour
  pullPolicy: Always
  tag: latest

service:
  type: ClusterIP
  port: 5000
  targetPort: 5000

ingress:
  enabled: true
  className: traefik
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: good-behaviour.jim00.pd.test-rig.nl
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: good-behaviour-tls
      hosts:
        - good-behaviour.jim00.pd.test-rig.nl

env:
  djangoDebug: "false"
  secretKey: CHANGE_ME
  allowedHosts: good-behaviour.jim00.pd.test-rig.nl,good-behaviour,localhost,*
  csrfTrustedOrigins: https://good-behaviour.jim00.pd.test-rig.nl
  corsAllowAll: "true"

postgres:
  host: ""
  port: "5432"
  database: goodbehaviour
  username: goodbehaviour
  password: CHANGE_ME

mtls:
  enabled: false
  requiredClientCN: kong-client
  caCert: ""
  serverCert: ""
  serverKey: ""
  clientCert: ""
  clientKey: ""

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

livenessProbe:
  enabled: true
  httpGet:
    path: /health/
    port: 5000
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  enabled: true
  httpGet:
    path: /health/
    port: 5000
  initialDelaySeconds: 10
  periodSeconds: 5

imagePullSecrets: []
podSecurityContext:
  fsGroup: 1000
securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
