#!/bin/bash
#
# Start Dogcatcher and Model Citizen locally with API key authentication
#
# This script:
#   1. Generates secure API keys if not already configured
#   2. Creates .env file if it doesn't exist
#   3. Starts the Docker Compose stack
#
# Usage:
#   ./scripts/start-local.sh [OPTIONS]
#
# Options:
#   -r, --regenerate    Regenerate API keys even if .env exists
#   -d, --detach        Run containers in background
#   -h, --help          Show this help message
#

set -euo pipefail

# Script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
ENV_FILE="${PROJECT_ROOT}/.env"

# Options
REGENERATE_KEYS=false
DETACH_MODE=false

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1" >&2
}

show_help() {
    head -20 "${BASH_SOURCE[0]}" | tail -16 | sed 's/^#//'
}

# Generate a secure random key
generate_key() {
    if command -v openssl &> /dev/null; then
        openssl rand -hex 32
    else
        # Fallback for systems without openssl
        cat /dev/urandom | LC_ALL=C tr -dc 'a-f0-9' | fold -w 64 | head -n 1
    fi
}

# Parse arguments
parse_args() {
    while [[ $# -gt 0 ]]; do
        case "$1" in
            -r|--regenerate)
                REGENERATE_KEYS=true
                shift
                ;;
            -d|--detach)
                DETACH_MODE=true
                shift
                ;;
            -h|--help)
                show_help
                exit 0
                ;;
            *)
                log_error "Unknown option: $1"
                show_help
                exit 1
                ;;
        esac
    done
}

# Create or update .env file
setup_env_file() {
    if [[ -f "${ENV_FILE}" ]] && [[ "${REGENERATE_KEYS}" == false ]]; then
        log_info "Using existing .env file"
        return
    fi

    log_info "Generating secure API keys..."

    # Generate keys
    local dogcatcher_api_key
    local admin_api_key
    local dogcatcher_secret
    local citizen_secret
    
    dogcatcher_api_key="$(generate_key)"
    admin_api_key="$(generate_key)"
    dogcatcher_secret="$(generate_key)"
    citizen_secret="$(generate_key)"

    # Create .env file
    cat > "${ENV_FILE}" << EOF
# Dogcatcher & Model Citizen Environment Configuration
# Generated by start-local.sh on $(date -u +"%Y-%m-%d %H:%M:%S UTC")

# =============================================================================
# API Keys Configuration
# =============================================================================

# API keys for Dogcatcher API (comma-separated)
# - citizen-app: Used by Model Citizen app
# - admin: For administrative access / testing
DOGCATCHER_API_KEYS=${dogcatcher_api_key},${admin_api_key}

# API key that Model Citizen uses (matches first key above)
CITIZEN_API_KEY=${dogcatcher_api_key}

# Require API key for all API requests
API_KEY_REQUIRED=true

# =============================================================================
# Application Secrets
# =============================================================================

DOGCATCHER_SECRET_KEY=${dogcatcher_secret}
CITIZEN_SECRET_KEY=${citizen_secret}

# =============================================================================
# URLs and Networking
# =============================================================================

DOGCATCHER_PUBLIC_URL=http://localhost:5001

# =============================================================================
# Development Settings
# =============================================================================

FLASK_DEBUG=true
EOF

    log_success "Created .env file with secure keys"
    
    echo ""
    log_info "Generated API Keys:"
    echo "  Citizen App Key: ${dogcatcher_api_key:0:16}..."
    echo "  Admin Key:       ${admin_api_key:0:16}..."
    echo ""
    log_warn "For API testing, use the admin key in the X-API-Key header"
}

# Check Docker is available
check_docker() {
    if ! command -v docker &> /dev/null; then
        log_error "Docker is not installed"
        exit 1
    fi

    if ! docker info &> /dev/null; then
        log_error "Docker daemon is not running"
        exit 1
    fi
}

# Start the stack
start_stack() {
    log_info "Starting Docker Compose stack..."

    cd "${PROJECT_ROOT}"

    local compose_args=("up")
    
    if [[ "${DETACH_MODE}" == true ]]; then
        compose_args+=("-d")
    fi

    docker-compose "${compose_args[@]}"
}

# Show access information
show_access_info() {
    echo ""
    log_success "Stack is starting!"
    echo ""
    echo "  Dogcatcher App:       http://localhost:5001"
    echo "  Dogcatcher API Docs:  http://localhost:5001/api/docs"
    echo "  Model Citizen:        http://localhost:5002"
    echo ""
    echo "  Demo CitID logins: DEMO, CIT001, CIT002, CIT003"
    echo ""
    
    if [[ -f "${ENV_FILE}" ]]; then
        # Extract admin key for display
        local admin_key
        admin_key=$(grep "^DOGCATCHER_API_KEYS=" "${ENV_FILE}" | cut -d'=' -f2 | cut -d',' -f2)
        if [[ -n "${admin_key}" ]]; then
            echo "  Test API with:"
            echo "    curl -H 'X-API-Key: ${admin_key}' http://localhost:5001/api/dogs/"
            echo ""
        fi
    fi
}

# Main
main() {
    parse_args "$@"
    check_docker
    setup_env_file
    
    if [[ "${DETACH_MODE}" == true ]]; then
        start_stack
        show_access_info
    else
        show_access_info
        echo "Press Ctrl+C to stop..."
        echo ""
        start_stack
    fi
}

main "$@"
