# Kong with OIDC Plugin
# Using revomatico/kong-oidc which is a maintained Kong image with OIDC support
#
# Note: This image includes the kong-oidc plugin pre-installed
# Source: https://github.com/revomatico/docker-kong-oidc
#
FROM revomatico/docker-kong-oidc:3.4.0-2

# The OIDC plugin is pre-installed in this image
# No additional configuration needed
